---
title: "Ataques Ciberneticos IPs y Puertos Vulnerables"
---

## Introducción

En un ecosistema emergente y con brechas disruptivas, el ciberespacio se hizo vulnerable por ataques cibernéticos ingresando a la OT - IT, esto nos lleva a mirar al futuro con mayor análisis y dar una visibilidad holística en cuanto se refiere a la ciberseguridad Industrial e Informática. Para ello vamos a tomar decisiones más inteligentes para las organizaciones a través de la DATA SCIENCE. 

## Antecedentes

Hace 20 años el 22 de julio de 1999 ocurrió un suceso oscuro en la historia de la computación, el primer ataque DDoS hasta la actualidad este va relacionando con los ataques de Ransomware RaaS con la triple extorción.

Para nuestro caso de estudio malware el conjunto de datos UNSW-NB15.

## Planteamiento del Problema

- ¿Cuáles son los ataques más frecuentes?
- ¿De dónde proceden los ataques más frecuentes?
- ¿Qué puertos son más vulnerables?

## Objetivo General

Analizar según nuestro dataset de la UNSW-NB15 los tipos de ataques cibernéticos más frecuentes, procedencia y puertos más vulnerables 

## Hipótesis 

- Identificar tipos de ataques más frecuentes
- Identificar la procedencia de los ataques por IPs
- Identificar los puertos más vulnerables 

## Análisis Exploratorio

### Datasets
### Standards
### Packages


